services:
  web:
    build:
      context: "."
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
          gitlab_rails['time_zone'] = "Asia/Tehran"
          gitlab_rails['backup_keep_time'] = 14515200
          gitlab_rails['smtp_pool'] = false
          gitlab_rails['gitlab_shell_ssh_port'] = 2224
          
          letsencrypt['enabled'] = false
          nginx['enable'] = true
          nginx['redirect_http_to_https'] = false
    
          external_url 'https://gitlab.parasite-resume.ir:8929'
          nginx['http2_enabled'] = false
          nginx['listen_port'] = 8929
          nginx['listen_https'] = false
          nginx['real_ip_header'] = 'X-Forwarded-For'
          nginx['real_ip_recursive'] = 'on'
          nginx['proxy_set_headers'] = {
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "on",
            "X-Forwarded-Protocol" => "https",
            "X-Url-Scheme" => "https",
          }
        
          registry_external_url "https://registry.parasite-resume.ir:8929"
          registry_nginx['http2_enabled'] = false
          registry_nginx['listen_port'] = 8929
          registry_nginx['listen_https'] = false
          registry_nginx['real_ip_header'] = 'X-Forwarded-For'
          registry_nginx['real_ip_recursive'] = 'on'
          registry_nginx['proxy_set_headers'] = {
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "on",
            "X-Forwarded-Protocol" => "https",
            "X-Url-Scheme" => "https",
          }
        
          puma['worker_processes'] = 0
        
          sidekiq['concurrency'] = 1
          sidekiq['max_concurrency'] = 2
        
          grafana['enable'] = false
          prometheus_monitoring['enable'] = false
          alertmanager['enable'] = false
        
          postgresql['shared_buffers'] = "256MB"
          postgresql['auto_restart_on_version_change'] = false
    hostname: gitlab.parasite-resume.ir
    image: "gitlab/gitlab-ee:latest"
    ports:
      - "8929:8929"
      - "2224:22"
    restart: always
    shm_size: 256m
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
version: "3.6"
