services:
  web:
    build:
      context: "."
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
          gitlab_rails['time_zone'] = "Asia/Tehran"
          gitlab_rails['backup_keep_time'] = 604800
          gitlab_rails['smtp_pool'] = false
          gitlab_rails['gitlab_shell_ssh_port'] = 2224
          gitlab_rails['rack_attack_git_basic_auth'] = {
            'enabled' => true,
            'ip_whitelist' => ["127.0.0.1"],
            'maxretry' => 10,
            'findtime' => 60,
            'bantime' => 3600
          }
          
          external_url 'https://gitlab.parasite-resume.ir/'
          nginx['redirect_http_to_https'] = true
          nginx['http2_enabled'] = false
          nginx['listen_port'] = 80
          nginx['listen_https'] = false
          nginx['add_headers'] = {
            "Access-Control-Allow-Origin" => "*",
            "Access-Control-Allow-Credentials" => "true",
            "Access-Control-Allow-Methods" => "GET, POST, OPTIONS, PUT, PATCH, DELETE",
            "Access-Control-Allow-Methods" => "DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type"
          }
          nginx['proxy_set_headers'] = {
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "off",
            "X-Forwarded-Protocol" => "https",
            "X-Forwarded-Host" => "gitlab.parasite-resume.ir",
            "X-Url-Scheme" => "https",
            "Access-Control-Allow-Origin" => "*",
            "Host" => "gitlab.parasite-resume.ir",
            "X-Real-IP" => "162.55.12.128",
            "X-Forwarded-For" => "162.55.12.128"
          }
        
          registry_external_url "https://registry.parasite-resume.ir/"
          registry_nginx['redirect_http_to_https'] = true
          registry_nginx['http2_enabled'] = false
          registry_nginx['listen_port'] = 80
          registry_nginx['listen_https'] = false
          registry_nginx['add_headers'] = {
            "Access-Control-Allow-Origin" => "*",
            "Access-Control-Allow-Credentials" => "true",
            "Access-Control-Allow-Methods" => "GET, POST, OPTIONS, PUT, PATCH, DELETE",
            "Access-Control-Allow-Methods" => "DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type"
          }
          registry_nginx['proxy_set_headers'] = {
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "off",
            "X-Forwarded-Protocol" => "https",
            "X-Forwarded-Host" => "registry.parasite-resume.ir",
            "X-Url-Scheme" => "https",
            "Access-Control-Allow-Origin" => "*",
            "Host" => "registry.parasite-resume.ir",
            "X-Real-IP" => "162.55.12.128",
            "X-Forwarded-For" => "162.55.12.128"
          }
        
          puma['worker_processes'] = 0
        
          sidekiq['concurrency'] = 1
          sidekiq['max_concurrency'] = 2
        
          grafana['enable'] = false
          prometheus_monitoring['enable'] = false
          alertmanager['enable'] = false
        
          postgresql['shared_buffers'] = "256MB"
          postgresql['auto_restart_on_version_change'] = false
    hostname: gitlab.parasite-resume.ir
    image: "gitlab/gitlab-ee:latest"
    ports:
      - "80:80"
      - "2224:22"
    restart: always
    shm_size: 256m
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
version: "3.6"
