version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    container_name: "gitlab"
    restart: always
    hostname: 'gitlab.parasite-resume.ir'
    build:
      context: .
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['proxy_protocol'] = true
        nginx['proxy_set_headers'] = {
  "X-Forwarded-Proto" => "http",
  "X-Frame-Options" => "SAMEORIGIN",
  "Content-Security-Policy" => "upgrade-insecure-requests",
  "Referrer-Policy" => "origin",
  "Access-Control-Allow-Origin" => "*",
  "Access-Control-Allow-Credentials" => "true",
  "Access-Control-Allow-Methods" => "GET, POST, OPTIONS, PUT, PATCH, DELETE",
  "Access-Control-Allow-Headers" => "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
 }
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'
        external_url 'https://gitlab.parasite-resume.ir:8929'
        nginx['listen_port'] = 8929
        nginx['listen_https'] = false
        registry_external_url "https://registry.parasite-resume.ir:8929"
        registry_nginx['listen_port'] = 8929
        registry_nginx['listen_https'] = false
        gitlab_rails['smtp_pool'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        puma['worker_processes'] = 1
        sidekiq['concurrency'] = 1
        sidekiq['max_concurrency'] = 2
        grafana['enable'] = false
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        postgresql['shared_buffers'] = "256MB"
        postgresql['auto_restart_on_version_change'] = false
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
# gitlab_rails['store_initial_root_password'] = true
